export const APP_ROUTES = {
  login: '/login',
  authCallback: '/auth/callback',
  dashboard: '/dashboard',
  trips: '/trips',
  tripCreate: '/trips/create',
  tripDetail: (id: string) => `/trips/${id}`,
  notifications: '/notifications',
  profile: '/profile',
  calendar: '/calendar',
  tasks: '/tasks',
  expenses: '/expenses',
  teams: '/teams',
  admin: '/teams',
} as const;
